name: CI

permissions:
  contents: read

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  MIX_ENV: test

jobs:
  build_and_test:
    name: Build and Test
    runs-on: groupcollect-runner
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Elixir/Erlang
        uses: erlef/setup-beam@v1.18.2
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Cache compiled build
        uses: actions/cache@v4
        with:
          path: _build
          key: ${{ runner.os }}-mix-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-build-

      - name: Install dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Check formatting
        run: mix format --check-formatted

      - name: Compile and fail on warnings
        run: mix compile --warnings-as-errors

      - name: Check for un-used dependencies
        run: mix deps.unlock --check-unused

      - name: Run tests
        run: mix test

      - name: Check for dependency security vulnerabilities
        run: mix deps.audit
        continue-on-error: true
